# .gitlab-ci.yml
# Повний CI/CD pipeline з усіма етапами, що проходять гейти.
# Призначений для локального GitLab-ранера з docker-executor.

# Визначення етапів (stages) конвеєра
stages:
  - secret-scan
  - sast
  - test
  - build
  - sca
  - deploy
  - dast

# Використання офіційних шаблонів GitLab для сканерів
include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/DAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

secret_detection:
  allow_failure: false
sast:
  allow_failure: false
unit_test_job:
  allow_failure: false
dependency_scanning:
  allow_failure: false
container_scanning:
  allow_failure: false

# =========================================================================
# ЕТАП: secret-scan
# =========================================================================
# Сканування репозиторію на наявність секретів.
secret_detection:
  stage: secret-scan
  needs: []

# =========================================================================
# ЕТАП: sast (Static Application Security Testing)
# =========================================================================
# Статичний аналіз коду на наявність вразливостей.
sast:
  stage: sast
  needs: []

# =========================================================================
# ЕТАП: test
# =========================================================================
# Запуск юніт-тестів.
unit_test_job:
  stage: test
  image: python:3.11-slim
  script:
    - echo "Running unit tests..."
    - pip install -r requirements.txt
    - pip install pytest
    - pytest test_app.py
  needs:
    - job: sast
      optional: true

# =========================================================================
# ЕТАП: build
# =========================================================================
# Створення образу Docker з додатком.
docker_build_job:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "Building Docker image..."
    # Авторизуємося в реєстрі контейнерів GitLab, використовуючи CI-змінні
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    # Створюємо образ і позначаємо його для завантаження в реєстр
    - docker build -t "$CI_REGISTRY_IMAGE" .
    # Відправляємо образ до реєстру
    - docker push "$CI_REGISTRY_IMAGE"
  needs: ["unit_test_job"]

# =========================================================================
# ЕТАП: sca (Software Composition Analysis) та sbom
# =========================================================================
# Аналіз залежностей та генерація SBOM.
dependency_scanning:
  stage: sca
  needs: ["docker_build_job"]

container_scanning:
  stage: sca
  variables:
    CS_IMAGE: $CI_REGISTRY_IMAGE
  needs:
    - docker_build_job
  services:
    - docker:20.10.16-dind

# =========================================================================
# ЕТАП: deploy
# =========================================================================
# Розгортання додатка. Цей етап повинен бути перед DAST.
deploy_job:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "Deploying the application..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull "$CI_REGISTRY_IMAGE"
    - docker run -d --name my-python-app -p 5000:5000 "$CI_REGISTRY_IMAGE"
    - echo "Application deployed locally at http://my-python-app:5000"
    - sleep 10
  needs: ["container_scanning"]

# =========================================================================
# ЕТАП: dast (Dynamic Application Security Testing)
# =========================================================================
# Динамічний аналіз працюючого додатка на вразливості.
dast:
  stage: dast
  variables:
    DAST_WEBSITE: http://my-python-app:5000
  needs: ["deploy_job"]
  services:
    - docker:20.10.16-dind
